event_inherited();
deadspr = spr_frogplat_dead;
palettespr = spr_noisepalette;
curpalette = 0;
bboxhmul = 0.25;
nohit = true;
addtosaveroom = false;
dir = image_xscale;
scale = 1;
alarm[0] = 120;
image_speed = 0.35;
fireid = -4;
skipcycle = false;
skipfirecycle = false;
loopsnd = event_instance("event:/sfx/enemy/fireplatloop");
